export const achievementData = [
    {
        achivement: 'AIR 2 , INTERNATIONAL Rank 5',
        title: 'Lagori',
        year: '2022',
        teamLeader: 'Sushant Phalke',
        operator: 'Shreyash Ingale, Rahul Shinde',
        pitCrews: ['Satish Mungle', 'Omkar Suralkar', 'Soham Bhokare','Jayesh Shinde'],
        image: '/images/2022 int.jpg',
        hostCity: '	Delhi, INDIA',
    },
    {
        achivement: 'AIR 6',
        title: 'Throwing Arrows Into Pot',
        year: '2021',
        teamLeader: 'Harshwardhan Lokhande',
        operator: 'Kunal Khairnar, Mandar Dalimbe',
        pitCrews: ['Sushant Phalke', 'Swarangi Thakare', 'Prajakta Khairmode'],
        image: '/images/2021.jpg',
        hostCity: '	Jimo, China',
    },
    {
        achivement: 'AIR 14',
        title: 'ROBO RUGBY 7s',
        year: '2020',
        teamLeader: 'Rohit Bangal',
        operator: 'Kunal Patil, Kunal Khairnar',
        pitCrews: [
            'Satyajeet Nalawade',
            'Harshwardhan Lokhande',
            'Akshay Darade',
        ],
        image: '/images/2020.jpg',
        hostCity: 'Suva, Fiji',
    },
    {
        achivement: 'JUDGES SPECIAL AWARD',
        title: 'SHARE THE KNOWLEDGE',
        year: '2019',
        teamLeader: 'Rohit Bangal',
        operator: 'Sagar Wadhai',
        pitCrews: ['Ganesh Chincholkar', 'Prathamesh Nalawade'],
        image: '/images/2019.webp',
        hostCity: 'Ulaanbaatar, Mongolia',
    },
    {
        achivement: 'SMART AND SIMPLE ROBOT',
        title: 'NÉM CÒN',
        year: '2018',
        teamLeader: 'Kaustubh Gunjal',
        operator: 'Saurabh Gunjal',
        pitCrews: ['Siddhant Sananse', 'Rohit Bangal'],
        image: '/images/2018.webp',
        hostCity: 'Ninh Bình, Vietnam',
    },
    {
        achivement: 'NATIONAL ROOKIE AWARD',
        title: 'CLEAN ENERGY',
        year: '2016',
        teamLeader: 'Sagar Jadhav',
        operator: 'Rahul Chavan',
        pitCrews: ['Akash Tayade', 'Nilesh karmankar', 'Sameer Sheikh'],
        image: '/images/2016.webp',
        hostCity: 'Bangkok, Thailand',
    },
];
